### ISSUE TITLE
请问是b站尚硅谷的那个视频吗 我也想学呢

### ISSUE THREAD

**Issue by homxuwang** [lxy-go/SpringBoot#1]

**Comment by llh4biggerworld** [comment]
附议，我也想知道是哪个视频

**Comment by longlybits1029** [comment]
SpringSecurity的项目没有啊

**Comment by longlybits1029** [comment]
https://www.bilibili.com/video/av39001751 这个是视频地址，大家可以分享下学习经验

**Comment by JiahuaLink** [comment]
视频找不到了呜呜呜

**Comment by cc-XiaoCheng** [comment]
视频没了，请问哪位有保存的，可以发给我一下吗？

**Comment by whongwei40** [comment]
视频没了，呜呜呜

**Comment by yanghui939** [comment]
加qq号1366676359------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sdojasd&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月31日(星期天) 中午11:40
收件人:&nbsp;&quot;lxy-go/SpringBoot&quot;<SpringBoot@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [lxy-go/SpringBoot] 请问是b站尚硅谷的那个视频吗 我也想学呢 (#1)
